apiVersion: skaffold/v4beta11
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local: 
    push: false
  artifacts:
    - image: mugishbeldar/client 
      context: client
      docker: 
        dockerfile: Dockerfile 
      sync:
        manual: 
          - src: 'src/**/*.js'
            dest: .
    - image: mugishbeldar/post 
      context: posts
      docker: 
        dockerfile: Dockerfile 
      sync:
        manual: 
          - src: '**/*.js'
            dest: .
    - image: mugishbeldar/event-bus 
      context: event-bus
      docker: 
        dockerfile: Dockerfile 
      sync:
        manual: 
          - src: '**/*.js'
            dest: .
    - image: mugishbeldar/query 
      context: query
      docker: 
        dockerfile: Dockerfile 
      sync:
        manual: 
          - src: '**/*.js'
            dest: .
    - image: mugishbeldar/moderation 
      context: moderation
      docker: 
        dockerfile: Dockerfile 
      sync:
        manual: 
          - src: '**/*.js'
            dest: .
    - image: mugishbeldar/comment 
      context: comments
      docker: 
        dockerfile: Dockerfile 
      sync:
        manual: 
          - src: '**/*.js'
            dest: .

